on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install Dependencies
        run: |
          pip install commonmark
      - name: Create Local Changes
        run: |
          set APP_ENV=production
          make site
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
          branch: gh-pages
      - name: Check output html
        run: |
          git checkout gh-pages
          cd _site
          cat index.html
          git branch -v
