on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          pip install commonmark
          make site

      - name: Confirm site is made
        run: ls
