on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install Dependencies
        run: |
          pip install commonmark

      - name: Set env variable date
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Create Local Changes
        run: |
          git checkout -b gh-pages
          make site

      - name: Announce Deploy
        run: |
          git config --local user.name "Soup@Github Actions"
          git config --local user.email davenlu1989@gmail.com
          sed -i 's/_site//' .gitignore
          git add .
          git commit -m 'deploy from github actions'
          git push
          echo "Deployed at $NOW"
